### ISSUE TITLE
Problems with paths in VisualStudio toolchain

### ISSUE THREAD

**Issue by bblaszkow06** [radiokit/bundlex#10]
There are several problems when using bundlex on Windows platform (tested on Win 10 and VSC++ 2015 Build Tools):
* `Bundlex.Toolchain.VisualStudio`, line 46: mkdir fails when the path exists, so it only works 1 time
* `Bundlex.Toolchain.VisualStudio`, line 46: this path is not surrounded by `"` and slashes are not converted to Windows format (actually, slashes may remain in form `/path/` as long as quotes are used)
* `Bundlex.Toolchain.VisualStudio`, line 48: same here

**Comment by mat-hek** [comment]
shouldn't this be closed by https://github.com/radiokit/bundlex/pull/18 ?
